#pragma once

namespace api
{
	enum class ERenderPassFormat
	{
		NONE = -1,

		COLOR_RENDERPASS,
		COLOR_FLOAT_RENDERPASS,
		DEPTH_RENDERPASS,
		DEPTH_FLOAT_RENDERPASS,
		DEPTH_STENCIL_RENDERPASS,
		DEPTH_STENCIL_FLOAT_RENDERPASS,
	};
}